### ISSUE TITLE
ERROR: clc_server is not a legal parameter in an Ansible task or handler

### ISSUE THREAD

**Issue by ernestgwilsonii** [CenturyLinkCloud/clc-ansible-module#11]
This works OK:
[root@VA1EWTPPP02 ~]# ansible all -i /usr/local/bin/clc_inv.py --list-hosts
    NY1EWTWRDPRS01
    VA1EWTPRSRN01
    VA1EWTSHTW01
    VA1EWTPPP02
    VA1EWTQQQ06
    VA1EWTPPP01
    VA1EWTRH6501
    NY1EWTSHTU02
    NY1EWTCMS01
    NY1EWTDRSRN01
    VA1EWTWRDPRSS01

This fails:
[root@VA1EWTPPP02 ~]# ansible-playbook -i /usr/bin/clc_inv.py my-playbook.yml
ERROR: clc_server is not a legal parameter in an Ansible task or handler
## Here was my my-playbook.yml
- name: Create a Linux Server with 3 GBs of app space
  hosts: localhost
  gather_facts: False
  connection: local
  tasks:
  - name: Create Server
    clc_server:
      name: test
      template: ubuntu-14-64
      count: 1
      group: 'Default Group'
      additional_disks:
        - {path: /myApp, sizeGB: 3, type: partitioned}
    register: clc
  - name: debug
    debug: var=clc

**Comment by markramach** [comment]
It looks like you have not identified the clc-ansible-module in the Ansible library path. The following is from the Ansible developing modules [documentation](http://docs.ansible.com/ansible/developing_modules.html)

```
 Modules can be written in any language and are found in the path specified by ANSIBLE_LIBRARY or the --module-path command line option.

 By default, everything that ships with ansible is pulled from its source tree, but additional paths can be added.

 The directory ”./library”, alongside your top level playbooks, is also automatically added as a search directory.
```
