### ISSUE TITLE
Regex selection of hosts fails when using nested group

### ISSUE THREAD

**Issue by WesWWagner** [CenturyLinkCloud/clc-ansible-module#15]
When attempting to use regex patterns to select hosts, I am getting inconsistent results. For example: "~S" will return: UC1ASBLSWRM01 and UC1ASBLSWRM02 , but a use of the pattern: "~SW" returns an empty set.

**Comment by bmh2git** [comment]
@WesWWagner when a host pattern with a tilde (~) is submitted to Ansible it will attempt to create a regex match-pattern from the sequence of characters which follow the tilde.  Try changing your pattern to `~.\*SW.\*`.  This should match on any group or server with "SW" in the name.

**Comment by WesWWagner** [comment]
Negative ... ~.SW. does not work... ~SW does not work, but for some reason ~S works (but only because it is a small environment and this is overly broad).  There seems to be some issue with host selection of CLC hosted hosts and regex patterns for hostnames.

**Comment by clc-runner** [comment]
Don't forget the *  so the pattern will be "~.*SW.*"

**Comment by WesWWagner** [comment]
That works. Odd inconsistent behavior when not fully qualified notwithstanding :) ... for example I can use ~APP and it pulls all my app servers just fine. ~DB pulls my db servers, but ~SWRM does not pull my docker swarm servers.  "~.(star)SWRM.(star)" does work, but it is definitely inconsistent behavior that is being driven by something.

It seems the workaround is more explicit regex patterns, but there is still something at play here.

**Comment by markramach** [comment]
I created a hosts file with the following setup.

```
 [APP]
 UC1ASBLSWRM01

 [DB]
 UC1ASBLSWRM02
```

A simple playbook.

```
 - hosts: ~.*SW.*
   tasks:
    - shell: uname
```

I was then able to select both servers for my play using the regular expression.

```
 mramach$ ansible-playbook -i hosts --list-hosts test.yml

 playbook: test.yml

   play #1 (~.*SW.*): host count=2
     UC1ASBLSWRM02
     UC1ASBLSWRM01
```

This should work as long as you are using a valid regular expression after the `~`

**Comment by WesWWagner** [comment]
I agree... the more specific regex pattern works. I am pulling servers dynamically from CenturyLink Cloud, rather than a static hosts file. Using the more specific regex pattern I get consistent results. Using less explicit patterns I get inconsistent results. Obviously the best practice answer is, "use the explicit pattern silly!" ... but someone else being lazy will bump into this. :)
