### ISSUE TITLE
support for custom python environments

### ISSUE THREAD

**Issue by cgeers** [CenturyLinkCloud/clc-ansible-module#17]
I have observed when using this ansible module within a custom python environment, the dependent clc_sdk library is not found.  After changing the shebang to allow the environment to determine the proper python interpreter, the clc_sdk is utilized normally.  

Pull request [https://github.com/CenturyLinkCloud/clc-ansible-module/pull/16] is intended to address this concern. Please let me know if more information is needed.

**Comment by cgeers** [comment]
Any thoughts on this? FWIW, I've given [https://github.com/CenturyLinkCloud/clc-ansible-module/pull/16] a cursory test locally without issue.

**Comment by jwcolbert** [comment]
I'm looking into this.

**Comment by jwcolbert** [comment]
Merged [#16]
