### ISSUE TITLE
On Empty Inventory, Inventory Script Endlessly Loops

### ISSUE THREAD

**Issue by piffey** [CenturyLinkCloud/clc-ansible-module#2]
When the inventory is empty, the clc_inv.py script endlessly loops on is_list_flat() since the while never hits, always returning false. I'll submit a pull request. 

Thanks for all the work you guys have been doing on these. Looking forward to more easy integration with CLC.

**Comment by brianalbrecht** [comment]
Merged your change.  Thanks for the help!

**Comment by piffey** [comment]
Looks like there might have been a regression with the updated version pushed. Endlessly looping on empty inventory again.
