### ISSUE TITLE
Error when using registered variables with clc_server

### ISSUE THREAD

**Issue by uzzz** [CenturyLinkCloud/clc-ansible-module#25]
I copied an example from a README, trying to run (ansible 1.9.4) it and i'm getting following error:

```
ERROR: multiple actions specified in task: 'register' and 'Create server'
```

Am I doing something wrong?

**Comment by markramach** [comment]
It could be an indentation issue with the task definition. Can you post the playbook content?

**Comment by uzzz** [comment]
Well, I just copied topmost example from readme:

```
---
- name: deploy ubuntu hosts at CLC (Yay!)
  hosts: localhost
  gather_facts: False
  connection: local
  tasks:
    - name: Insure that exactly 3 Ubuntu servers are running in Default Group
      clc_server:
        name: test
        template: ubuntu-14-64
        exact_count: 3
        group: 'Default Group'
        count_group: 'Default Group'
      register: clc
    - name: debug
      debug: var=clc.server_ids
```

and ran it with

`ansible-playbook -i /usr/local/bin/clc_inv.py example.yml`

**Comment by markramach** [comment]
Is this the complete playbook, or just a segment you added to the playbook?

**Comment by uzzz** [comment]
Sorry, this issue isn't related to the clc-ansible-module. I believe it's because I set custom module search path. You can close this issue.
