### ISSUE TITLE
clc-publicip module throwing error on source restrictions

### ISSUE THREAD

**Issue by sdwhite** [CenturyLinkCloud/clc-ansible-module#26]
Receiving the following error trying to apply a public IP to hosts, the invocation seems to be correct so believe there is an issue somewhere in the code. Playbook attached below.

fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_args": {"ports": [8834], "protocol": "TCP", "server_ids": ["UC1WFTCLCSCN19", "WA1WFTCLCSCN21"], "source_restrictions": ["155.70.39.101/32", "155.70.39.45/32"], "state": "present"}, "module_name": "clc_publicip"}, "msg": "unsupported parameter for module: source_restrictions"}

[add_publicip.txt](https://github.com/CenturyLinkCloud/clc-ansible-module/files/188428/add_publicip.txt)

**Comment by popurisiva** [comment]
Are you using the latest version for clc-ansible-module? the source_restrictions argument has been added to the clc_publicip module recently. This error usually happens when the playbook is using the older version of clc-ansible-module code.

**Comment by jufkes** [comment]
Along with Siva's comment, I was able to run your playbook (changing the server names) successfully leading it to possibly be a result of an older version on your local system.

**Comment by sdwhite** [comment]
I did update the clc-ansible module, just ran it again, the installation of clc-sdk throws an error, so that may be the cause, I'll will investigate that.

**Comment by sdwhite** [comment]
The following shows the results of the update, I am still getting the same error message.
Successfully installed clc-ansible-module-1.1.4 clc-sdk-2.44

**Comment by sdwhite** [comment]
Found that my Ansible installation actually has the CLC module included in the file structure, specifically, /usr/local/lib/python2.7/dist-packages/ansible/modules/extras/cloud/centurylink/clc_publicip.py

This is the older version and it's picking that up.
