### ISSUE TITLE
Iterating Over Registered server_ids With No Changes Fails

### ISSUE THREAD

**Issue by piffey** [CenturyLinkCloud/clc-ansible-module#4]
The changed_server_ids in the clc_server.py module is created as None, then overwritten later. Only issue with this is that if you are iterating over a registered task's results it picks up null as an item to iterate over and the following task fails. Creating that as an empty list takes care of that. I'll submit another pull request since that's an easy and quick one.

**Comment by bmh2git** [comment]
piffey - we have published a [new release](https://github.com/CenturyLinkCloud/clc-ansible-module)  of the modules which includes your early contributions as well as enhancements which address the recent issues you found.

**Comment by piffey** [comment]
Awesome, thank you!
