### ISSUE TITLE
Support for clc-go-cli

### ISSUE THREAD

**Issue by dstrebel** [CenturyLinkCloud/clc-ansible-module#7]
Support for new clc-go-cli

**Comment by bmh2git** [comment]
dstrebel -  
The ansible modules are written in Python for better integration with the Ansible product.  In fact, the majority of the CLC-Ansible modules that exist today have been incorporated into Ansible-Extra and will be available as part of the Ansible product.  To this end we leveraged the clc-python-sdk to have a consistent implementation throughout.

Is there a particular bit of functionality which is only available via the clc-go-cli which you would like to see exposed through the clc-ansible-modules?

~Ben
