### ISSUE TITLE
Failed to connect to the host via ssh

### ISSUE THREAD

**Issue by lrajula** [CenturyLinkCloud/clc-ansible-module#76]
Hi Team,

I would like to use clc dynamic inventory script so that I can execute/perform actions on that servers.Following are the ansible version details.
  ansible 2.2.0.0
  config file = /etc/ansible/ansible.cfg
While executing below command after my credentials are set as environment variables, says "Failed to connect to the host via ssh"

command : ansible all -i inventory/clc_inv.py -m ping.

**Comment by jwcolbert** [comment]
Hello,

When you say that you have your credentials set as environment variables, are you referring to your CLC V2 credentials? 

Please note that the dynamic inventory script does not return password information for your servers. You would still need to have SSH keys setup on the servers that you are trying to access.

**Comment by lrajula** [comment]
Yes, I have referrred as CLC V2 credentials.

**Comment by jwcolbert** [comment]
Ok. Do you have SSH keys setup on the servers you are attempting to access? Dynamic inventory will only retrieve your inventory from CLC, you must still ensure that you have an access method for those servers and have established connectivity either via public IP or VPN.

**Comment by jwcolbert** [comment]
As we have heard nothing further regarding this I am closing this issue.
