### ISSUE TITLE
Server state: stopped should use Shutdown instead of Power Off when available

### ISSUE THREAD

**Issue by bgeihsgt** [CenturyLinkCloud/clc-ansible-module#8]
When setting a server's state to stopped, the code currently does a PowerOff to turn off the server.  This is the equivalent of turning the computer off via the power button.  Shutdown is a graceful OS shutdown that should be preferred.  Not all servers have shutdown capability, so the stopped state should use Shutdown when available and fall back to PowerOff if Shutdown is not available.

**Comment by bmh2git** [comment]
@bgeihsgt Thanks for your suggestion.  We are going to move ahead with your suggestion.  This change will be in our next release of the modules.

**Comment by bgeihsgt** [comment]
Sounds great!

**Comment by bmh2git** [comment]
This changed has been released in version 1.1.0.
